### PR TITLE
tostring() has been deprecated

### PR DESCRIPTION
**Pull request by rajathkumarmp**
Solves the error : 

```
Exception: tostring() has been removed. Please call tobytes() instead.
```

### CODE REVIEW

**Comment by tboggs** [comment]
Thanks for the pull request. This fixes the call for the Pillow fork but do you know if it breaks compatibility with PIL under Python 2 and/or 3?

**Comment by rajathkumarmp** [comment]
@tboggs I have used python2 haven't tested with python3.

**Comment by tboggs** [comment]
I'm not too worried about python3 at this point (there are other compatibility issues that will need to be fixed first) but I don't want to break compatibility with PIL (possibly older versions). Could you revise your pull request to fall back to `tostring` in case `tobytes` fails? Perhaps something like this:
```
try:
    img = images[i].tobytes("raw", "RGBX", 0, -1)
except:
    img = images[i].tostring("raw", "RGBX", 0, -1)
```
I'll open an issue and use your pull request to close it. To close the bug with the pull request, perhaps you could apply your fix to the two other locations where `tostring` is used (once each in rasterwindow.py and spywxpythonthread.py).

Thanks,
Thomas

**Comment by rajathkumarmp** [comment]
@tboggs  Sure thing.

**Pull request merged**
