### PR TITLE
as per request

### PR DESCRIPTION
**Pull request by YannChemin**
Loads Relab library basic info, does not load type, class and subclass
some code using ignorefiles is not needed

### CODE REVIEW

**Comment by LaurentBerder** [comment]
I have extensively tested it, and it works very well.
Can we merge it in the master?

**Comment by YannChemin** [comment]
Hi @tboggs, any update on this side?

**Comment by tboggs** [comment]
Hi @YannChemin, apologies for the delay. I'm away from my dev system for a few days. I'll review & test this by next week.

**Comment by tboggs** [comment]
The code looks good to me but before merging to master, please add some basic unit tests for creating and querying a Relab database. You should be able to copy most of the test code from one of the other databases in this file (you can also add the unit tests to the same file).

**Comment by YannChemin** [comment]
This is done, test added

**Comment by YannChemin** [comment]
@tboggs

**Comment by tboggs** [comment]
@YannChemin Thanks for adding the unit tests. I will have time to test the code in the next day or two and merge into master.

In the meantime, could you please rename the `relabDatabase` class to `RelabDatabase` to maintain [pep8 compliance](https://peps.python.org/pep-0008/#class-names) for class names?

**Comment by YannChemin** [comment]
OK done @tboggs

**Comment by tboggs** [comment]
@YannChemin, I'm ready to look at this now. Are PR #158 and #160 identical, just merging to different branches?

**Pull request merged**
