### PR TITLE
Fix USGS database for python 2.6

### PR DESCRIPTION
**Pull request by kormang**
Python 2.6 requires indices in format specs.

### CODE REVIEW

**Comment by kormang** [comment]
Because of personal reasons, this week I couldn't even read emails. Sorry about that.
Now that everything is back to normal I'm planning to do two more PRs.
I'd like to implement SMACC algorithm.
I would also like to finish support for python3.

Well, about python versions, why support python 2.6 anyway? Isn't 2.7 preinstalled on every Linux distro and MacOS as well? Python 2 in general is completely deprecated, is there any specific reason to bother supporting even more obsolete version?

**Comment by kormang** [comment]
[This line ](https://github.com/spectralpython/spectral/blob/c0c9b80f764612a16b1e0cd8d9abb2d7b82f1b31/spectral/algorithms/algorithms.py#L1808) will also fail on python 2.6.
I'm pretty sure the right way to go is to stop supporting 2.6. Otherwise bugs like this will not stop popping up. Other potential contributors have python 2.7 preinstalled, and it is highly unlikely they will test their code with python 2.6, just like I did. Especially because there is no official declaration which python 2 version is supported.

**Comment by kormang** [comment]
I see that builds for 2.6 and 3.3 are preformed on Ubuntu 14.04, which is also deprecated. However, I know some of the biggest and most famous tech companies are still using it, to my surprise. However, it is still questionable if Spectral Python should support it.

**Comment by kormang** [comment]
Ping. Is this OK?

**Comment by tboggs** [comment]
I'm afk for a few days. Will take a look at this in more detail this weekend. Thanks.

**Pull request merged**
